feat(t31): add Map to MapPool Form UI
LogiXide/ra2-leaderboards-frontend pull request #26
Opened 2023-04-05 15:03 UTC by AlekseySamokhin

This is an unfinished version. This is an example for you to have. For discussion on the call.

2023-04-14 17:08 UTC, killmenot commented on modules/core/components/common/ItemList/ItemList.tsx
> +type FieldType = {
rename: itemType

2023-04-14 17:09 UTC, killmenot commented on modules/core/components/common/ItemList/ItemList.tsx
> +  fields: FieldType[];
rename: items or list

2023-04-14 17:09 UTC, killmenot commented on modules/core/components/common/ItemList/ItemList.tsx
> +export const ItemList: React.FC<PropsType> = (props) => {
rename: ItemsList

2023-04-14 17:10 UTC, killmenot commented on modules/core/components/common/ItemList/ItemList.tsx
> +          mt: '10px',
mt: 1

2023-04-14 17:10 UTC, killmenot commented on modules/core/components/common/MapPoolMaps/MapPoolMaps.tsx
> +import { ItemList } from '../ItemList';
use absolute import

2023-04-14 17:12 UTC, killmenot commented on modules/core/components/common/MapPoolMaps/MapPoolMaps.tsx
> +type FieldType = {
it should be a Map not FieldType

2023-04-14 17:16 UTC, killmenot commented on modules/core/components/common/MapPoolMaps/MapPoolMaps.tsx
> +  const availableFields = useMemo(() => {
This one is wrong
1. don't compare by name (u have ids)
2. depends on data and fields
3. the logic of transformation
   a. make a map id (number) - selected (boolean)
   b. map data items and return a new type which contains id, name and selected (boolean) based on map by id

2023-04-14 17:18 UTC, killmenot commented on modules/core/components/common/MapPoolMaps/MapPoolMaps.tsx
> +  fields: FieldType[];
rename:
fields -> selectedMaps
onSelectField / onRemoveField -> onChecked(item, checked: boolean)

2023-04-14 17:19 UTC, killmenot commented on modules/core/components/forms/fields/TextFieldNew/TextField.tsx
> +import MUITextField from '@mui/material/TextField';
refactor: don't forget to get rid of it (could be done later)

2023-04-14 17:19 UTC, killmenot commented on modules/maps/api/mapPools/mutations.ts
> +
empty space is not needed

2023-04-14 17:20 UTC, AlekseySamokhin commented on modules/core/components/common/MapPoolMaps/MapPoolMaps.tsx
> +  const availableFields = useMemo(() => {
1. I can't figure out why the fields object looks like this -> {id: 'aeec03a1-7892-4113-8cfb-69f5f9637cec', name: 'Divide Freezes Over (PreCaptured)', checked: true}.

2023-04-14 17:20 UTC, killmenot commented on modules/maps/components/MapPoolForm/MapPoolForm.tsx
> +  const onSelectField = (field: FieldType) => {
refactor: useCallback

2023-04-14 17:20 UTC, killmenot commented on modules/maps/components/MapPoolForm/MapPoolForm.tsx
> +  const onRemoveField = (field: FieldType) => {
refactor: useCallback

2023-04-14 17:21 UTC, killmenot commented on modules/maps/components/MapPoolForm/MapPoolForm.tsx
> +                {...field}
not sure what we need to pass  {...field}

2023-04-14 17:22 UTC, killmenot commented on pages/map-pools/[mapPoolId].tsx
> +  const convertDataToFields = useMemo(() => {
it could be utility function outside the component

2023-04-14 17:23 UTC, AlekseySamokhin commented on modules/maps/components/MapPoolForm/MapPoolForm.tsx
> +                {...field}
ок

2023-04-14 17:23 UTC, AlekseySamokhin commented on pages/map-pools/[mapPoolId].tsx
> +  const convertDataToFields = useMemo(() => {
utils?

2023-04-14 17:23 UTC, killmenot requested changes
Please take a look at my notes

2023-04-14 17:24 UTC, killmenot commented on pages/map-pools/[mapPoolId].tsx
> +  const convertDataToFields = useMemo(() => {
yeah, just create a function outside the component

2023-04-17 18:27 UTC, killmenot commented on modules/core/components/common/MapPoolMaps/MapPoolMaps.tsx
> +  items: MapType[];
you can pass maps and transform them to ItemType type from ItemsList

2023-04-17 18:28 UTC, killmenot commented on modules/core/components/common/ItemsList/ItemsList.tsx
> +type ItemType = {
export this type

2023-04-17 18:31 UTC, killmenot commented on modules/maps/components/MapPoolForm/MapPoolForm.tsx
> +              sx={{ textTransform: 'capitalize' }}
we don't need textTransform here

2023-04-17 18:32 UTC, killmenot approved these changes

2023-04-20 18:23 UTC, merged