feat(t27): crud for map pools ui
LogiXide/ra2-leaderboards-frontend pull request #8
Opened 2023-03-19 16:46 UTC by AlekseySamokhin

Added the ability to add and update card pools.
For add map pool, I created a button 'add map pool' on the page on click, which opens a modal window with an extension to add a name.
For update map pool, I created a new page, the transition to which is carried out by clicking on the map pool in table.
Please let me know if something is wrong.

2023-03-19 19:13 UTC, killmenot commented on modules/mapPools/api/mutations/createMapPool.ts
> +import { gql } from '@apollo/client';
the module should have the same name like we have on backend

modules/maps/api
 - mapPools (folder)
    - mutations.ts
    - queries.ts
 - maps (folder)
  ....

2023-03-19 19:14 UTC, killmenot commented on modules/mapPools/components/forms/FormCreateMapPool.tsx
> +    const timeout = setTimeout(() => {
useTimeout always bad

2023-03-19 19:14 UTC, killmenot requested changes
please see inline comments

2023-03-20 14:19 UTC, AlekseySamokhin commented
I changed the structure according to your comments. And also removed from the code setTimeout();

2023-03-20 21:06 UTC, AlekseySamokhin commented
@killmenot CRUD for maps to do or wait for a conversation on Wednesday?

2023-03-20 21:09 UTC, killmenot commented
You can work on it

2023-03-21 07:05 UTC, merged